"use client";

export const dynamic = "force-dynamic";

import { useCallback, useEffect, useState } from "react";
import { Download, Loader2 } from "lucide-react";

import { SectionShell, EmptyState } from "@/components/of-intelligence/SectionShell";
import { useAuthFetch } from "@/hooks/use-auth-fetch";
import { ofiApi, type ExportResponse, type MemoryEntryRow, formatRelative } from "@/lib/of-intelligence/api";

export default function OfIntelligenceMemoryBankPage() {
  const { fetchWithAuth } = useAuthFetch();
  const [rows, setRows] = useState<MemoryEntryRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [exportPath, setExportPath] = useState("");
  const [lastExport, setLastExport] = useState<ExportResponse | null>(null);

  const refresh = useCallback(async () => {
    try {
      setRows(await ofiApi.memory(fetchWithAuth, 100));
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setLoading(false);
    }
  }, [fetchWithAuth]);

  useEffect(() => { void refresh(); }, [refresh]);

  const onExport = useCallback(async () => {
    setBusy(true);
    setError(null);
    try {
      const res = await ofiApi.exportMemory(fetchWithAuth, {
        export_path: exportPath.trim() || undefined,
        mirror_to_memory: true,
      });
      setLastExport(res);
      await refresh();
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
    } finally {
      setBusy(false);
    }
  }, [fetchWithAuth, exportPath, refresh]);

  return (
    <SectionShell
      title="Memory Bank"
      description="Structured business-memory entries that AI agents can search later. Export to Obsidian for human-readable navigation."
      actions={
        <div className="flex items-center gap-2">
          <input
            type="text"
            placeholder="/path/to/Obsidian vault (optional)"
            value={exportPath}
            onChange={(e) => setExportPath(e.target.value)}
            className="rounded-md border px-3 py-1.5 text-sm w-72"
            style={{ background: "var(--bg)", borderColor: "var(--border)", color: "var(--text)" }}
          />
          <button
            type="button"
            onClick={() => void onExport()}
            disabled={busy}
            className="inline-flex items-center gap-1.5 rounded-md px-3 py-1.5 text-sm font-medium disabled:opacity-50"
            style={{ background: "var(--accent-strong)", color: "white" }}
          >
            {busy ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Download className="h-3.5 w-3.5" />}
            Export
          </button>
        </div>
      }
    >
      {error && (
        <div className="mb-4 rounded-md border p-3 text-sm" style={{ borderColor: "rgb(248,113,113)", color: "rgb(225,29,72)" }}>
          {error}
        </div>
      )}

      {lastExport && (
        <div
          className="mb-4 rounded-md border p-3 text-sm"
          style={{ borderColor: "var(--border)", color: "var(--text-muted)" }}
        >
          Exported {lastExport.file_count} files into <code>{lastExport.obsidian_root}</code>.
          Wrote {lastExport.written_to_disk.length} to disk; skipped {lastExport.skipped.length}.
        </div>
      )}

      {loading ? (
        <EmptyState title="Loading memory entries…" />
      ) : rows.length === 0 ? (
        <EmptyState
          title="Memory bank is empty."
          hint="Memory entries are auto-generated by QC reports and exports. Generate a QC report or run an export to populate."
        />
      ) : (
        <ul className="space-y-2">
          {rows.map((r) => (
            <li
              key={r.id}
              className="rounded-xl border p-4"
              style={{ background: "var(--surface)", borderColor: "var(--border)" }}
            >
              <div className="flex items-start justify-between gap-3">
                <div className="min-w-0">
                  <p className="text-sm font-medium" style={{ color: "var(--text)" }}>{r.title}</p>
                  <p className="text-xs mt-0.5" style={{ color: "var(--text-quiet)" }}>
                    {r.kind} · {formatRelative(r.created_at)} {r.obsidian_path ? `· ${r.obsidian_path}` : ""}
                  </p>
                </div>
              </div>
            </li>
          ))}
        </ul>
      )}
    </SectionShell>
  );
}
